name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    # --- INICIO DE MODIFICACIÓN ---
    # Define las variables de entorno para producción aquí.
    # Estas variables estarán disponibles durante el 'npm run build'.
    env:
      NEXT_PUBLIC_API_URL: 'https://api.scieluxe.com/api'
      NEXT_PUBLIC_DEFAULT_COMPANY_ID: '1' # ID de la compañía para producción
      NEXT_PUBLIC_DEFAULT_USER_ID: '54'   # ID del usuario para producción
    # --- FIN DE MODIFICACIÓN ---
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        # Ya no se necesita el bloque 'env' aquí, porque se define a nivel del 'job'
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0A993100F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # Ruta del código fuente de la aplicación
          api_location: "" # Ruta del código de la API (opcional)
          output_location: ".next" # Directorio de salida de Next.js
          app_build_command: "npm run build" # Comando para construir la aplicación
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_0A993100F }}
          action: "close"